### ISSUE TITLE
expose play.http.context in CMAK

### ISSUE THREAD

**Issue by leozleung** [eshepelyuk/cmak-operator#11]
I want to change the context path of the UI to work behind ingress.
is it possible to expose the "play.http.context" in values.yaml?

**Comment by eshepelyuk** [comment]
I'll take a look and will feedback soon.

**Comment by eshepelyuk** [comment]
Hi,
I have to implement a possibility to override default CMAK config via config map.
I think I could do it this weekend.

**Comment by leozleung** [comment]
Thanks! i will test on it once the release is tagged

**Comment by eshepelyuk** [comment]
I am waiting for #14 and #15 to make a single release.

**Comment by eshepelyuk** [comment]
@leozleung released [1.0.0](https://github.com/eshepelyuk/cmak-operator/releases/tag/1.0.0)

**Comment by leozleung** [comment]
@eshepelyuk tested and it works as expected! thanks!
