### ISSUE TITLE
Custom JMX PORT

### ISSUE THREAD

**Issue by danschreifels2019** [eshepelyuk/cmak-operator#13]
Is there an option to change the JMX port to a custom port?  I use AWS MSK and the default JMX port is 1101.  where can I change that?

**Comment by eshepelyuk** [comment]
Does CMAK suport it on its own ?

**Comment by eshepelyuk** [comment]
There's open question in CMAK 
https://github.com/yahoo/CMAK/issues/762

Feel free to ask there, this project can't support port change unless CMAK itself supports it.
Closing the issue.
