### ISSUE TITLE
passing array instead of string in ui.extraArgs

### ISSUE THREAD

**Issue by leozleung** [eshepelyuk/cmak-operator#19]
how can I pass array like basicAuthentication.excluded=["/cmak/api/health"] in ui.extraArgs ? seems everyting will convert to string

**Comment by eshepelyuk** [comment]
I believe this question is not related to this project. It is all about CMAK and its configuration management.

**Comment by eshepelyuk** [comment]
I suppose you could try reading
https://github.com/lightbend/config#set-array-values-outside-configuration-files

**Comment by leozleung** [comment]
thanks! I will close this issue
