### ISSUE TITLE
image retention in dockerhub

### ISSUE THREAD

**Issue by oferzi23** [eshepelyuk/cmak-operator#32]
i see you are deleting images from dockerhub. last week i was still able to install 1.3.0 but now images are deleted from there. can we set a longer retention period there? keeping last 2 majors can result in chart breaking every couple of weeks. this will not make this really available for production use....

**Comment by eshepelyuk** [comment]
I am not touching images
1.3.0 is still there
https://hub.docker.com/r/eshepelyuk/json2zk/tags?page=1&ordering=last_updated

**Comment by oferzi23** [comment]
https://hub.docker.com/r/eshepelyuk/cmak2zk/tags?page=1&ordering=last_updated

**Comment by eshepelyuk** [comment]
It is used, too. I didn't delete any images manually and have no intention to do it in future.
Closing the issue.
