### ISSUE TITLE
Support latest version of cmak

### ISSUE THREAD

**Issue by benmathews** [eshepelyuk/cmak-operator#47]
The latest version supports new versions of kafka
https://github.com/yahoo/CMAK/pull/871

**Comment by eshepelyuk** [comment]
Hello

1. CMAK didnt release a new version with this feature yet.
2. The chart needs a docker image to run pod in k8s
3. This chart doesnt build cmak image but uses this docker https://github.com/hleb-albau/kafka-manager-docker
4. Currently chart doesnt allow to override default images with custom ones

So, until CMAK releases official new version I tend not to use the latest code from master branch, and also corresponding docke image repository must be addressed.

If you want to try to build docker image from the master and try it with this chart, it is required to make change to support CMAK docker image overide via values file, so PR is welcomed.

**Comment by eshepelyuk** [comment]
Some updates
I started working on some internal changes to the project that will result in support of the latest CMAK version as one of the consequences.

**Comment by visla-xugeng** [comment]
@eshepelyuk Hi, when do you think we can use the latest operator to support CMAK 3.0.0.6, since we are using kafka 3.1.0.

**Comment by eshepelyuk** [comment]
> @eshepelyuk Hi, when do you think we can use the latest operator to support CMAK 3.0.0.6, since we are using kafka 3.1.0.

i plan to release it smth about next week.

**Comment by visla-xugeng** [comment]
@eshepelyuk Thanks for the update. 👍
