### ISSUE TITLE
Ability to change CMAK to read only mode.

### ISSUE THREAD

**Issue by jitapichab** [eshepelyuk/cmak-operator#55]
Hi, Nice project :)

I want to put the CMAK in read only mode to change:

application.features=["KMClusterManagerFeature","KMTopicManagerFeature","KMPreferredReplicaElectionFeature","KMReassignPartitionsFeature"]

for
application.features=["KMPreferredReplicaElectionFeature”,“KMReassignPartitionsFeature"] and vice-versa.

What do you think about (overwrite application.conf option )

there is another wat to put CMAK in read only mode ?

Thanks a lot !!!

**Comment by eshepelyuk** [comment]
Hello

There is a dedicated section in README about`application.conf` customization.

https://github.com/eshepelyuk/cmak-operator#cmak-application-settings
