### ISSUE TITLE
Add `ingressClassName` field for ingress

### ISSUE THREAD

**Issue by d-mankowski-synerise** [eshepelyuk/cmak-operator#57]
Annotation to specify ingress class, `kubernetes.io/ingress.class`, has been [deprecated](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation) for quite some time and it is recommended to use `spec.ingressClassName` instead. 

This would just require to add one field in https://github.com/eshepelyuk/cmak-operator/blob/master/templates/ingress.yaml

**Comment by eshepelyuk** [comment]
Hi @d-mankowski-synerise 

PR is welcome.

**Comment by d-mankowski-synerise** [comment]
@eshepelyuk  Hi, PTAL at #58 - I am not very familiar with helm charts development, so hopefully it is fine :)

**Comment by eshepelyuk** [comment]
Thnx for the contribution @d-mankowski-synerise 
Available in 2.2.0

**Comment by d-mankowski-synerise** [comment]
thanks!
