### ISSUE TITLE
Allow docker registry to be overridden

### ISSUE THREAD

**Issue by graphex-sumo** [eshepelyuk/cmak-operator#6]
With docker pull limits these days, it would be nice if the image could be pulled from an alternate repository provided in values.

**Comment by eshepelyuk** [comment]
Excuse me, but I can't understand the purpose of the issue from this description.

Pease provide 
* Detailed description of the problem you're experiencing currently
* Detailled description of the proposed change with examples of its usage
* Explanation about how proposed change could solve current problem

Also, I'd like to remind that contributions are welcomed.

Thnx in advance.

**Comment by graphex-sumo** [comment]
I'm working on a PR for this right now. The issue is that the images used in the helm chart are hardcoded in the templates without the ability to override the location in the values file. The Docker image registry has implemented rate limiting on docker pulls from its repository, and many companies who run things at scale have set up mirrors to host docker images so that there is no risk of being unable to deploy a tool due to Docker image pull rate limiting. I am proposing value overrides for the images used in this helm chart which allow end users to switch to using their own repos and tags. I'll have a PR for this soon.

**Comment by eshepelyuk** [comment]
Hello @graphex-sumo 
Thanks for the explanation. Never experienced that, so missed the override values.
Plz provide the PR, be aware that there is 3 different images involved in this setup.
Ask me if you need any help on the PR.

**Comment by eshepelyuk** [comment]
@graphex-sumo  fixed in https://github.com/eshepelyuk/cmak-operator/releases/tag/0.8.0

**Comment by eshepelyuk** [comment]
@graphex-sumo any feedback for #6 and #7 ?
