### ISSUE TITLE
helm repo add problem: is not a valid chart repository or cannot be reached

### ISSUE THREAD

**Issue by maverickdb** [eshepelyuk/cmak-operator#63]
I'm trying to use this helm chart, but it seem that there is a problem:

`# helm repo add cmak-operator https://eshepelyuk.github.io/cmak-operator/`
`Error: looks like "https://eshepelyuk.github.io/cmak-operator/" is not a valid chart repository or cannot be reached: failed to fetch https://eshepelyuk.github.io/cmak-operator/index.yaml : 404 Not Found`

It's quite perplexing that I seem to be the only one experiencing this issue. I've made attempts to resolve it on multiple computers where I have Helm installed, yet the error persists consistently across all of them

Thanks in advance.

**Comment by maverickdb** [comment]
Following your doc: https://artifacthub.io/packages/helm/kubegemsapp/cmak I was able to install it without adding repo.

**Comment by eshepelyuk** [comment]
1. the repository you referred is a scam, you are using it on your own risk.
2. installation instructions are provided in readme, i have no idea why you hadn't used it.
