### ISSUE TITLE
Allow usage as a subchart

### ISSUE THREAD

**Issue by graphex-sumo** [eshepelyuk/cmak-operator#7]
In cases where global values are provided or if this chart is included as a subchart (even if no globals are actually specified), the values schema is overly restrictive and fails validation.

**Comment by eshepelyuk** [comment]
Dear @graphex-sumo 

https://github.com/eshepelyuk/cmak-operator/issues/6#issuecomment-752207746

**Comment by eshepelyuk** [comment]
@graphex-sumo  fixed in https://github.com/eshepelyuk/cmak-operator/releases/tag/0.8.0
